// ─────────────────────────────────────────────
// Smart Todo — Core Data Types
// ─────────────────────────────────────────────

/** User-facing priority label (set by user at capture time) */
export type Priority = "low" | "medium" | "high" | "critical";

/** Task lifecycle status */
export type TaskStatus = "pending" | "in_progress" | "done" | "waiting";

/** Item type discriminator */
export type ItemType = "task" | "note";

/** Source of capture */
export type NoteSource = "manual" | "voice" | "media_capture" | "share_intent";

// ── Media ──────────────────────────────────

export interface MediaAttachment {
  id: string;
  uri: string;
  type: "image" | "audio" | "file";
  mimeType?: string;
  fileName?: string;
  createdAt: string; // ISO 8601
}

// ── Recurrence ─────────────────────────────

export type RecurrenceFrequency =
  | "daily"
  | "weekly"
  | "monthly"
  | "yearly"
  | "custom";

/** 0 = Sunday … 6 = Saturday (same as JS Date.getDay()) */
export type DayOfWeek = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export interface RecurrenceRule {
  frequency: RecurrenceFrequency;
  interval: number; // 1 = every occurrence, 2 = every other, etc.
  daysOfWeek?: DayOfWeek[] | null;
  dayOfMonth?: number | null;
  endDate?: string | null; // ISO 8601 — null means "forever"
  exceptions?: string[]; // ISO 8601 dates to skip
}

// ── Semantic Link ──────────────────────────

export interface SemanticLink {
  id: string;
  fromId: string;
  toId: string;
  similarity: number; // 0.0 – 1.0
  autoGenerated: boolean;
  createdAt: string; // ISO 8601
}

// ── Checklist (notes only) ─────────────────

export interface ChecklistItem {
  id: string;
  text: string;
  checked: boolean;
}

// ── Base Item (shared by Task & Note) ──────

export interface ItemBase {
  id: string; // UUID
  type: ItemType;
  title: string;
  content: string; // markdown / plain text
  media: MediaAttachment[];
  embedding: number[] | null; // 384-dim float vector
  tags: string[];
  createdAt: string; // ISO 8601
  updatedAt: string; // ISO 8601
  archivedAt: string | null; // ISO 8601
  links: SemanticLink[];
}

// ── Task ───────────────────────────────────

export interface Task extends ItemBase {
  type: "task";
  userPriority: Priority;
  importance: number; // 0.0–1.0, adaptive, computed
  dueDate: string | null; // ISO 8601
  isAllDay: boolean;
  recurrence: RecurrenceRule | null;
  parentId: string | null; // self-referential FK for sub-tasks
  subtasks: Task[]; // children (loaded on demand)
  completedSubtasks: number; // denormalized count
  completedAt: string | null; // ISO 8601
  status: TaskStatus;
  lastTouchedAt: string | null; // ISO 8601
}

// ── Note ───────────────────────────────────

export interface Note extends ItemBase {
  type: "note";
  pinned: boolean;
  color: string; // hex color for visual grouping
  checklist: ChecklistItem[] | null;
  source: NoteSource;
  lastTouchedAt: string | null; // ISO 8601
}

// ── Union type ─────────────────────────────

export type Item = Task | Note;

// ── Helper type guards ─────────────────────

export function isTask(item: Item): item is Task {
  return item.type === "task";
}

export function isNote(item: Item): item is Note {
  return item.type === "note";
}

// ── Priority base weights (used by importance scorer) ──

export const PRIORITY_BASE_WEIGHT: Record<Priority, number> = {
  low: 0.25,
  medium: 0.5,
  high: 0.75,
  critical: 1.0,
};

// ── Factory helpers ────────────────────────

export function createTaskBase(
  title: string,
  userPriority: Priority = "medium"
): Omit<Task, "subtasks"> {
  const now = new Date().toISOString();
  return {
    id: crypto.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`,
    type: "task",
    title,
    content: "",
    media: [],
    embedding: null,
    tags: [],
    createdAt: now,
    updatedAt: now,
    archivedAt: null,
    links: [],
    userPriority,
    importance: PRIORITY_BASE_WEIGHT[userPriority],
    dueDate: null,
    isAllDay: true,
    recurrence: null,
    parentId: null,
    completedSubtasks: 0,
    completedAt: null,
    status: "pending",
    lastTouchedAt: now,
  };
}

export function createNoteBase(title: string): Note {
  const now = new Date().toISOString();
  return {
    id: crypto.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`,
    type: "note",
    title,
    content: "",
    media: [],
    embedding: null,
    tags: [],
    createdAt: now,
    updatedAt: now,
    archivedAt: null,
    links: [],
    pinned: false,
    color: "#FFFFFF",
    checklist: null,
    source: "manual",
    lastTouchedAt: now,
  };
}
